import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Arctic Glass design tokens
        background: "#0a0e1a",
        "on-background": "#e0e8f0",
        surface: "#0f1524",
        "surface-dim": "#0f131f",
        "surface-bright": "#1a2438",
        "surface-variant": "#1a2438",
        "surface-container-lowest": "#0a0e1a",
        "surface-container-low": "#111828",
        "surface-container": "#141c2e",
        "surface-container-high": "#1a2438",
        "surface-container-highest": "#202c42",
        "on-surface": "#e0e8f0",
        "on-surface-variant": "#a0b4c4",
        "inverse-surface": "#e0e8f0",
        "inverse-on-surface": "#0a0e1a",
        "surface-tint": "#7dd3fc",
        outline: "#4a6070",
        "outline-variant": "#2a3a48",
        primary: "#7dd3fc",
        "on-primary": "#001f2e",
        "primary-container": "#0e4d6e",
        "on-primary-container": "#c8eaff",
        "primary-fixed": "#c8eaff",
        "primary-fixed-dim": "#7dd3fc",
        "on-primary-fixed": "#001f2e",
        "on-primary-fixed-variant": "#004d73",
        "inverse-primary": "#0a4c6e",
        secondary: "#88b4cc",
        "on-secondary": "#001f2e",
        "secondary-container": "#1a3a4e",
        "on-secondary-container": "#c0d8e8",
        "secondary-fixed": "#c0d8e8",
        "secondary-fixed-dim": "#88b4cc",
        "on-secondary-fixed": "#0d1f2b",
        "on-secondary-fixed-variant": "#2a4a5e",
        tertiary: "#c8a0f0",
        "on-tertiary": "#1a002e",
        "tertiary-container": "#3d2060",
        "on-tertiary-container": "#e8d0ff",
        "tertiary-fixed": "#e8d0ff",
        "tertiary-fixed-dim": "#c8a0f0",
        "on-tertiary-fixed": "#1a002e",
        "on-tertiary-fixed-variant": "#4d2a73",
        error: "#ff6b6b",
        "on-error": "#1a0000",
        "error-container": "#3d1414",
        "on-error-container": "#ffb3b3",
        // Legacy aliases kept for any leftover references
        brand: {
          50: "#c8eaff",
          100: "#7dd3fc",
          200: "#0e4d6e",
          300: "#0a4c6e",
          400: "#004d73",
          500: "#7dd3fc",
          600: "#001f2e",
          700: "#111828",
          800: "#0f1524",
          900: "#0a0e1a",
        },
      },
      fontFamily: {
        sans: ["var(--font-inter)", "system-ui", "sans-serif"],
        display: ["var(--font-inter)", "system-ui", "sans-serif"],
        headline: ["var(--font-inter)", "system-ui", "sans-serif"],
        body: ["var(--font-inter)", "system-ui", "sans-serif"],
        label: ["var(--font-inter)", "system-ui", "sans-serif"],
      },
      spacing: {
        sidebar: "16rem",
        header: "4rem",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        xl: "1rem",
        "2xl": "1.5rem",
      },
      boxShadow: {
        soft: "0 2px 8px -2px rgb(0 0 0 / 0.08), 0 4px 16px -4px rgb(0 0 0 / 0.06)",
        lift: "0 8px 24px -6px rgb(0 0 0 / 0.18), 0 2px 6px -2px rgb(0 0 0 / 0.12)",
        glow: "0 0 30px rgba(125, 211, 252, 0.05)",
        "glow-sm": "0 0 15px rgba(125, 211, 252, 0.1)",
        "glow-md": "0 0 25px rgba(125, 211, 252, 0.15)",
      },
      keyframes: {
        "fade-in": {
          from: { opacity: "0", transform: "translateY(10px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "scale-in": {
          from: { opacity: "0", transform: "scale(0.96)" },
          to: { opacity: "1", transform: "scale(1)" },
        },
        "slide-up": {
          from: { opacity: "0", transform: "translateY(8px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        "fade-in": "fade-in 0.5s ease-out forwards",
        "scale-in": "scale-in 0.18s cubic-bezier(0.16,1,0.3,1)",
        "slide-up": "slide-up 0.22s cubic-bezier(0.16,1,0.3,1)",
      },
    },
  },
  plugins: [],
};

export default config;
