import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Arctic Glass design tokens — CSS-variable driven for dark/light
        background: "rgb(var(--background))",
        "on-background": "rgb(var(--on-background))",
        surface: "rgb(var(--surface))",
        "surface-dim": "rgb(var(--surface-dim))",
        "surface-bright": "rgb(var(--surface-bright))",
        "surface-variant": "rgb(var(--surface-variant))",
        "surface-container-lowest": "rgb(var(--surface-container-lowest))",
        "surface-container-low": "rgb(var(--surface-container-low))",
        "surface-container": "rgb(var(--surface-container))",
        "surface-container-high": "rgb(var(--surface-container-high))",
        "surface-container-highest": "rgb(var(--surface-container-highest))",
        "on-surface": "rgb(var(--on-surface))",
        "on-surface-variant": "rgb(var(--on-surface-variant))",
        "inverse-surface": "rgb(var(--inverse-surface))",
        "inverse-on-surface": "rgb(var(--inverse-on-surface))",
        "surface-tint": "rgb(var(--surface-tint))",
        outline: "rgb(var(--outline))",
        "outline-variant": "rgb(var(--outline-variant))",
        primary: "rgb(var(--primary))",
        "on-primary": "rgb(var(--on-primary))",
        "primary-container": "rgb(var(--primary-container))",
        "on-primary-container": "rgb(var(--on-primary-container))",
        "primary-fixed": "rgb(var(--primary-fixed))",
        "primary-fixed-dim": "rgb(var(--primary-fixed-dim))",
        "on-primary-fixed": "rgb(var(--on-primary-fixed))",
        "on-primary-fixed-variant": "rgb(var(--on-primary-fixed-variant))",
        "inverse-primary": "rgb(var(--inverse-primary))",
        secondary: "rgb(var(--secondary))",
        "on-secondary": "rgb(var(--on-secondary))",
        "secondary-container": "rgb(var(--secondary-container))",
        "on-secondary-container": "rgb(var(--on-secondary-container))",
        "secondary-fixed": "rgb(var(--secondary-fixed))",
        "secondary-fixed-dim": "rgb(var(--secondary-fixed-dim))",
        "on-secondary-fixed": "rgb(var(--on-secondary-fixed))",
        "on-secondary-fixed-variant": "rgb(var(--on-secondary-fixed-variant))",
        tertiary: "rgb(var(--tertiary))",
        "on-tertiary": "rgb(var(--on-tertiary))",
        "tertiary-container": "rgb(var(--tertiary-container))",
        "on-tertiary-container": "rgb(var(--on-tertiary-container))",
        "tertiary-fixed": "rgb(var(--tertiary-fixed))",
        "tertiary-fixed-dim": "rgb(var(--tertiary-fixed-dim))",
        "on-tertiary-fixed": "rgb(var(--on-tertiary-fixed))",
        "on-tertiary-fixed-variant": "rgb(var(--on-tertiary-fixed-variant))",
        error: "rgb(var(--error))",
        "on-error": "rgb(var(--on-error))",
        "error-container": "rgb(var(--error-container))",
        "on-error-container": "rgb(var(--on-error-container))",
        // Legacy aliases kept for any leftover references
        brand: {
          50: "#c8eaff",
          100: "#7dd3fc",
          200: "#0e4d6e",
          300: "#0a4c6e",
          400: "#004d73",
          500: "#7dd3fc",
          600: "#001f2e",
          700: "#111828",
          800: "#0f1524",
          900: "#0a0e1a",
        },
      },
      fontFamily: {
        sans: ["var(--font-inter)", "system-ui", "sans-serif"],
        display: ["var(--font-inter)", "system-ui", "sans-serif"],
        headline: ["var(--font-inter)", "system-ui", "sans-serif"],
        body: ["var(--font-inter)", "system-ui", "sans-serif"],
        label: ["var(--font-inter)", "system-ui", "sans-serif"],
      },
      spacing: {
        sidebar: "16rem",
        header: "4rem",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        xl: "1rem",
        "2xl": "1.5rem",
      },
      boxShadow: {
        soft: "0 2px 8px -2px rgb(0 0 0 / 0.08), 0 4px 16px -4px rgb(0 0 0 / 0.06)",
        lift: "0 8px 24px -6px rgb(0 0 0 / 0.18), 0 2px 6px -2px rgb(0 0 0 / 0.12)",
        glow: "0 0 30px rgba(125, 211, 252, 0.05)",
        "glow-sm": "0 0 15px rgba(125, 211, 252, 0.1)",
        "glow-md": "0 0 25px rgba(125, 211, 252, 0.15)",
      },
      keyframes: {
        "fade-in": {
          from: { opacity: "0", transform: "translateY(10px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "scale-in": {
          from: { opacity: "0", transform: "scale(0.96)" },
          to: { opacity: "1", transform: "scale(1)" },
        },
        "slide-up": {
          from: { opacity: "0", transform: "translateY(8px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        "fade-in": "fade-in 0.5s ease-out forwards",
        "scale-in": "scale-in 0.18s cubic-bezier(0.16,1,0.3,1)",
        "slide-up": "slide-up 0.22s cubic-bezier(0.16,1,0.3,1)",
      },
    },
  },
  plugins: [],
};

export default config;
